server:
  port: 8080

eureka:
  client:
    fetch-registry: true 
    registry-with-eureka: true 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: playlistRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
